### ISSUE TITLE
Possible IllegalArgumentException at line 69 and 81 at RetrieveLeaderboard.java? 

### ISSUE THREAD

**Issue by Septillihedron** [orang3-juic3/nerdrolebot#2]
If the string length inside the addField's second argument are larger than the MessageEmbed.VALUE_MAX_LENGTH, it will throw an IllegalArgumentException

Did i do this right?

**Comment by orang3-juic3** [comment]
Could you tell me where this would be thrown?

**Comment by orang3-juic3** [comment]
Oops i didnt read the title...

**Comment by orang3-juic3** [comment]
This would never be thrown because the maximum length of a username is 32. There are 10 usernames in the !list max, 10 * 32 is 320 which is less than the limit.
https://discordjs.guide/popular-topics/embeds.html

**Comment by Septillihedron** [comment]
But if someone use the !lead @'s (it could be bigger than 10 people) or the message count is bigger, it could happen (because each line also contains the rank number and the message count)
